### ISSUE TITLE
Icon size and stroke width slider not visible in Firefox

### ISSUE THREAD

**Issue by manish-basargekar** [artcoholic/akar-icons-app#2]
# This is what I see in Firefox

![image](https://user-images.githubusercontent.com/64839201/214256607-49d7351c-3f10-4009-baef-b045f39467d2.png)

# Compared to Chrome
![image](https://user-images.githubusercontent.com/64839201/214257235-4a2770fb-6fa0-4ae9-b5f4-eee01a0230a4.png)

Also, thank you for awesome icons!

**Comment by artcoholic** [comment]
Hi @manish-basargekar, thank you for catching this issue. I've fixed the stroke in Firefox.
